[package]
name = "rcc-dump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bitflags = "2.4.1"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
inflate = "0.4.5"
nom = "7.1.3"
thiserror = "1.0.50"
zstd = { version = "0.13.0", features = ["experimental"] }
